#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:0 h:2 toc:1
# num:0 = dont number any, h:2 = headings to level 2, toc:1 = only put a table of contents to level 1
#+TITLE:     Unit Vocabulary
#+AUTHOR:    Alex Burns
# EXPORT = C-c C-e h h

# https://github.com/fniessen/refcard-org-mode
# /Emphasize/ (italics), *strongly* (bold), and */very strongly/* (bold italics), \\ = return

* Unit 1
*** Bit: A contraction of "Binary Digit"; the single unit of information in a computer, typically represented as a 0 or 1
*** Byte: 8 bits: 10010101
*** Overflow Error:  Error from attempting to represent a number that is too large
*** Round-off Error:  Error from attempting to represent a number that is too precise. The value is rounded off.
*** Abstraction: We create simplified representations of something more complex. Representing text is an example of abstraction.
*** Analog Data: Data values that change continuously, or smoothly, over time. Some examples of analog data include music, colors of a painting, or position of a sprinter during a race.
*** Digital Data:  data that changes discreetly through a fine set of possible values.
*** Sampling:  A process for creating a digital representation of analog data by measuring the analog data at regular intervals called samples
*** Lossless Compression: A process for reducing the number of bits needed to represent something without losing any information. This process is reversible
*** Lossy Compression:  A process for reducing the number of bits needed to represent something in which some information is lost or thrown away. This process is not reversible.
*** Creative Commons: a license that allows you to freely use materials created by others
*** Open Source: programs that are made freely available and may be redistributed and modified
*** Open Access: online research output free of restrictions to access and use

* Unit 2
*** Net Neutrality: Internet service providers should enable access to all content and applications regardless of source, and without favoring or blocking particular products or websites
*** Internet Censorship: the attempt to control or suppress of what can be accessed, published, or viewed on the internet by certain people. This can be used to protect people (such as children) but can also be used to limit free speech
*** Computing Device: a machine that can run a program, including computers, tablets, servers, routers, and smart sensors
*** Computing System: a group of computing devices and programs working together for a common purpose
*** Computing Network: a group of interconnected computing devices capable of sending or receiving data
*** Path: The series of connections between computing devices on a network starting with a sender and ending with a receiver
*** Bandwidth: the maximum amount of data that can be sent in a fixed amount of time, usually measured in bits per second
*** Protocol: An agreed-upon set of rules that specify the behavior of some system
*** IP Address: The unique number assigned to each device on the internet
*** Internet Protocol (IP): a protocol for sending data across the internet that assigns unique numbers (IP addresses) to each connected device
*** Router: A type of computer that forwards data across a network
*** Redundancy: the inclusion of extra components so that a system can continue to work even if individual components fail, for example by having more than one path between any two connected devices in a network
*** Fault Tolerant: Can continue to function even in the event of individual component failures. This is important because elements of complex systems like a computer network fail at unexpected times, often in groups
*** DataStream: information passed through the internet as packets
*** Packet: A chunk of data sent over a network. Larger messages are divided into packets that may arrive at the destination in order, out of order, or not at all
*** Packet Metadata: Data added to packets to help route them through the network and reassemble the original message
*** Transmission Control Protocol (TCP): a protocol for sending packets that does error-checking to ensure all packets are received and properly ordered
*** User Datagram Protocol (UDP): a protocol for sending packets quickly with minimal error-checking and no resending of dropped packets
*** Scalability: the capacity for the system to change in size and scale to meet new demands
*** Domain Name System (DNS): the system responsible for translating domain names like example.com into IP addresses
*** World Wide Web: a system of linked pages, programs, and files
*** Hypertext Transfer Protocol (HTTP): a protocol for computers to request and share the pages that make up the world wide web on the internet
