#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:0 h:2 toc:1
# num:0 = dont number any, h:2 = headings to level 2, toc:1 = only put a table of contents to level 1
#+TITLE:     Vocabulary
#+AUTHOR:    Alex Burns
# EXPORT = C-c C-e h h

# https://github.com/fniessen/refcard-org-mode
# /Emphasize/ (italics), *strongly* (bold), and */very strongly/* (bold italics), \\ = return

* Chapter 1 Vocab:

** Section 2:
*** Unitary System: a system of government that gives all key powers to the nation/central government
*** Federal System: divides the powers of government between the national government and the state or principal government
*** Confederacy: a loose union of independent states
*** Constitution: a plan that provides rules for government
*** Constitutional Government: refers to a government in which a constitution has authority to place clearly recognized limits on the powers of those who govern
*** Preamble: a statement that sets forth the goals and purposes to be served by the government
*** Constitutional law: involves the interpretation and application of the constitution. Defines the extent and limits of government and rights of citizens
*** Politics: the effort to control or influence the conduct and policies of government
*** Industrialized nations: have generally large industries and advanced technology that provide a more comfortable way of life than developing nations
*** Developing nations: are only beginning to develop industry. Typically when a nation is first starting, these nations tend to be poorer than industrialized nations

** Section 3:
*** Autocracy: any system of government in which the power and authority to rule are in the hands of a single individual
*** Monarchy: another form of autocratic government. In a monarchy, a kind queen or emporer exercises the supreme power of government
*** Oligarchy: any system of government in which a small group holds power
*** Democracy: any system of government in which rule is byt he people
*** Republic: voters are the source of the governments authority
*** Political Party: a group of individuals with broad common interests who organize to nominate canidates for office, win elections, conduct government and determine public policy
*** Free Enterprise: the opportunity to control one's economic decisions

** Section 4:
*** Economics: the study of human efforts to satisfy seemingly unlimited wants through the use of limited resources
*** Capitalism: the system of free enterprise, freedom of choice and individual incetntive for workers
*** Free market: buyers and sellers are free to make unlimited economic decisions in the marketplace
*** Laissez-faire Economy: to be let alone, government should keep their hands off the economy
*** Socialism: the government owns the basic means of production, determines the use of resources, distributes the products and wages, and provides social services such as education and health care
*** Bourgeoise: own the means of production, aka capitalists
*** Proletariat: work to produce the goods, aka workers
*** Communism: one class exists, property would all be held in common, and there would be no need for government
*** Command Economy: decisions are made at the upper levels of government and handed down to managers

* Chapter 2 Vocab:

** Section 1:
*** Limited Government: the power of the monarch, or government, was limited and not absolute
*** Representative Government: a government in which people elect delegates to make laws and conduct government
*** Separation of powers: divided power of government so that there were checks and balances between the branches
*** Magna Carta: great charter that provided the basis for the principle of limited government to king john in 1215
*** Petition of right: Severly limited the king's power in 1628
*** English Bill of Rights: a document that was later very important to american colonies which set clear limits on what a ruler can and can not do
*** Mayflower Compact: signed in 1620, stands as the first example of many colenial plans for self-government
*** Great Fundamanetals: the first basic system of laws in the english colonies in 1636

** Section 2:
*** Revenue: the money a government collects from taxes or other sources
*** Embargo: an agreement prohibiting trade against a country, in this case britian
*** Stamp Act: the first direct tax on colonists. Required them to pay a tax on legal documents, pamphlets, newspapers etc in 1765
*** Intolerable Acts: Closed the boston harbor, removed self-government from massachusetts. A set of laws against the colonists in response to the boston tea party
*** Albany Plan of Union: an inovative plan for uniting the colonies, but it was rejected because it gave too much power to an assemably of representatives
