#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:0 h:2 toc:1
# num:0 = dont number any, h:2 = headings to level 2, toc:1 = only put a table of contents to level 1
#+TITLE:     Vocabulary
#+AUTHOR:    Alex Burns
# EXPORT = C-c C-e h h

# https://github.com/fniessen/refcard-org-mode
# /Emphasize/ (italics), *strongly* (bold), and */very strongly/* (bold italics), \\ = return

* Unit 1
*** Bit: A contraction of "Binary Digit"; the single unit of information in a computer, typically represented as a 0 or 1
*** Byte: 8 bits: 10010101
*** Overflow Error:  Error from attempting to represent a number that is too large
*** Round-off Error:  Error from attempting to represent a number that is too precise. The value is rounded off.
*** Abstraction: We create simplified representations of something more complex. Representing text is an example of abstraction.
*** Analog Data: Data values that change continuously, or smoothly, over time. Some examples of analog data include music, colors of a painting, or position of a sprinter during a race.
*** Digital Data:  data that changes discreetly through a fine set of possible values.
*** Sampling:  A process for creating a digital representation of analog data by measuring the analog data at regular intervals called samples
*** Lossless Compression: A process for reducing the number of bits needed to represent something without losing any information. This process is reversible
*** Lossy Compression:  A process for reducing the number of bits needed to represent something in which some information is lost or thrown away. This process is not reversible.
*** Creative Commons: a license that allows you to freely use materials created by others
*** Open Source: programs that are made freely available and may be redistributed and modified
*** Open Access: online research output free of restrictions to access and use
* Unit 2
