#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:0 h:2 toc:2
# num:0 = dont number any, h:2 = headings to level 2, toc:1 = only put a table of contents to level 1
#+TITLE:     Macbeth Act Questions
#+AUTHOR:    Alex Burns
# EXPORT = C-c C-e h h

# https://github.com/fniessen/refcard-org-mode
# /Emphasize/ (italics), *strongly* (bold), and */very strongly/* (bold italics), \\ = return

* Act 1
** Scene 1:
*** What effect is Shakespeare creating by beginning the play with this scene?
**** Shakespeare is creating the effect of conflict through the thunder and lightning, as well as good vs evil with the witches. He also sets the theme of the play through the words “Fair is Foul, and Foul is fair”. Creating suspense and mystery from the weird sisters.

*** What is the meaning of the line, “Fair is foul, and foul is fair”?
**** Fair is good looking on the in and out, and foul is bleh/gross. The meaning is that those who appear on the outside to be fair are actually on the inside foul(up to no good) while those who appear foul on the outside are fair. Things are not as they appear, and are in reality opposites.

*** What poetic device is used in this scene and to what effect?
**** Alliteration was used in this scene (F in fair foul fog and filthy), it allows the audience to consider and think about the meaning since the alliteration draws attention to it and emphasizes the witches base slovenliness.

** Scene 2:
*** What is the purpose of this scene?
**** The purpose of this scene is that Duncan, who is the king of Scotland, hears of the victory of the war thanks to Macbeth and Banquo, and sends messengers to Macbeth to congratulate him and give him thane of Cawdor. We also learn of Macbeth as being a hero as he is brave

*** What image do readers have of Macbeth’s bravery and ability as a warrior?
**** We have the image that Macbeth is a hero who willingly risks his life as he charges into battle when the enemies swarm Macbeth and Banquo. That he is fearless, and a good man fighting for his country.

*** Who had Macbeth and Banquo been fighting?
**** Macbeth and Banquo were fighting soldiers of Norway and a rebellion led by Macdonwald.

*** What does King Duncan tell Ross to do?
**** King Duncan tells Ross to give Macbeth thane of Cawdor since the person who was originally the thane died in battle. Ross is basically king Duncan’s messenger as he is sent of to tell Macbeth of his new position/news

** Scene 3:
*** What does the audience learn about the Weird Sisters from their conversation at the beginning of the scene?
**** The audience learns that the Weird Sisters are creating a storm because of someone that disrespected them. We get the impression that they are powerful and mischievous.

*** When Macbeth says, “So foul and fair a day I have not seen,” to what is he referring? What could be the dramatic irony in this line?
**** Macbeth is referring to the battle and the people that died along with him as foul, but their victory as fair. The dramatic irony is that he has not seen the foul and fair part of the day yet, as the witches telling him what he will be (thane of Cawdor, king) etc is actually a curse on his mentality as now he feels as he must do whatever he can to achieve it.

*** What prophecies do the Weird Sisters make regarding Macbeth? How does he react?
**** They make the prophecies that Macbeth will become Thane of Cawdor and King afterwards. He reacts by being intrigued while Banquo tells them to be quiet and he doesn't care about what they say.

*** What do the Weird Sisters see in the future for Banquo?
**** The weird sisters see that the son’s of Banquo will become kings after Macbeth's death. They will take over the thrown.

*** How do Macbeth and Banquo react to the experience after the Weird Sisters vanish?
**** Banquo thinks that they came and went and that it doesn't matter what they say. They consider that the meds they took are causing delusions and corrupting their minds. Then they joke around with each other.

*** What “terms” does Ross indicate accompany the title Thane of Cawdor?
**** That he is both thane of cawdor and thane of glamis. He also states that the Thane of Cawdor is the most worthy thane, as it is thine.

*** As the others talk, what does Macbeth’s aside reveal about his thinking?
**** Macbeth’s aside reveals that he is curious and even thought about killing the king to fulfill his prophecy. He is starting to believe what the witches told him and he thinks it is too real and that it is his new destiny. Essentially becoming mentally crazy
*** How does Banquo’s comment support the “Fair is foul, foul is fair” theme?

**** Banquo’s comment supports the theme that he should be careful and not believe everything that he hears, which ultimately leads him to killing Duncan with the help of his manipulative wife. He is saying that while this all sounds great on the outside, something bad would likely come as a result of it.

*** What does Macbeth mean in his aside about two truths being prologue to the act of the imperial theme?
**** Macbeth means that both things that the witches said (thane of cawdor and king) will both come true, and that he will become the king (imperial theme). Macbeth in his aside means that these things sound good but there must be an ill that comes with them (cannot be ill, cannot be good)

*** What dramatic conventions does Shakespeare use to establish character and begin to lay out his tragedy?
**** Shakespeare uses a constant back and forth of Macbeth’s ideas/opinions to establish that he does not have the ruthlessness to kill king Duncan, and that he himself would decide not to kill Duncan. It lays out the tragedy of someone else convincing him to do so, as Banquo convinces him that his thoughts are ridiculous and that he is crazy and needs to rethink what happened as a single strange occurrence.

** Scene 4:
*** Why was the former Thane of Cawdor executed?
**** The former Thane of Cawdor was executed because of his sins and that he confessed his treasons (Deserved to die).

*** What effect does Shakespeare create by having Macbeth and Banquo enter just as they are discussing the execution of the former Thane of Cawdor?
**** Shakespeare creates the effect of misplaced trust, which adds to the theme of the play. Macbeth enters after Duncan reflects as he thought he was a great man but he turned out evil which almost foreshadows the man who Macbeth is going to become.

*** What announcement does the King make to everyone present and what is Macbeth’s reaction?
**** The king makes the announcement that Malcolm is going to become king after Duncan instead of Macbeth, that Malcolm is the new heir to the throne. Macbeth tells duncan that he is going to tell his wife of there approach, trying to get out of there as fast as possible, but he is actually thinking (below).

*** In his last speech in this scene, what does Macbeth reveal?
**** Macbeth realizes that he must retreat and never become king or to kill both Duncan and Malcolm in order to secure the throne. Plants his thoughts of murder in his mind.

** Scene 5:
*** What is the purpose of the letter?
**** The purpose of the letter is to let Lady Macbeth know about the witches and what they said and how he as become thane of cawdor etc, and then she later finds out that Duncan is staying at there place.

*** What do readers learn about Macbeth from Lady Macbeth’s reaction to the letter?
**** Readers learn that Macbeth is too kind of a person to kill Duncan, as he is currently too loyal to do so. She knows that he is going to make his mind up against killing him.

*** What do readers learn about Lady Macbeth from her reaction to the letter?
**** Readers learn that Lady Macbeth is ruthless. She doesn't say that she is happy her husband didn't die or proud of him, she instead instantly starts thinking of how to kill Duncan, and decides on doing so without having a second thought.

*** Does Lady Macbeth fear Macbeth will not be king if he does not murder Duncan?
**** Yes, Lady Macbeth wants to be queen so much that she will not let anything get in the way of her husband becoming King.

*** How does the news about King Duncan’s expected arrival affect her? What is she planning?
**** It leads her to start planning his murder. She realizes that the easiest place to do something like this is in her own home, since they would be the ones protecting him and watching over him instead of his servants.

*** Why does Lady Macbeth pray to be unsexed? Explain.
**** Lady Macbeth prays to be unsexed because she believes that women are not cruel enough to do such a deed, while men are. She wants to become a man inorder to kill Duncan herself. Again, she is doing anything for her husband to be king.

*** What does Shakespeare establish in Macbeth and Lady Macbeth’s first exchange when Macbeth arrives home?
**** Shakespeare establishes that Duncan will not see the sun of the next morning and that by saying all-hail hereafter! She is going to do everything to become queen and she fully believes its Macbeth’s destiny.

*** In what way does Lady Macbeth’s advice to Macbeth relate to the “fair is foul” theme?
**** Lady Macbeth’s advice to appear like a flower but be a serpent on the inside relates to the theme of the novel in that those who appear nasty have good intentions while those who are fake have bad intentions. Parallels to social media today and “Float like a butterfly, sting like a bee” from cars. (haha)

** Scene 6:
*** What is the purpose of this brief scene?
**** The purpose of this scene is to set the scene that Duncan is happy to be staying at macbeths as he things he is the best man he knows, a hero, brave, etc. Then they run into lady macbeth which sets the scene later where macbeth isnt there.

*** How does this scene contribute to the “fair is foul” theme?
**** The scene contributes to the theme in that Lady Macbeth appears super friendly and nice as usual even though she is scheming to murder him in his sleep.

** Scene 7:
*** What arguments does Macbeth raise for not killing Duncan?
**** Macbeth raises the arguments that he should not kill Duncan because he does not want karma or a chain of violence to come back to him, and the Duncan does not know that he is his enemy because Macbeth is his kinsman and his host, who should be the ones protecting him from someone murdering him.

*** What does he finally conclude?
**** He finally concludes to not murder Duncan and that doing so would lead to bad consequences.

*** What consequences does Macbeth fear if he commits the murder?
**** He fears that he himself might be killed by Duncan’s sons or that nothing is stopping others from killing him. Also that if he gets caught then they will likely be killed.

*** What does Lady Macbeth say in an attempt to goad her husband into the murder?
**** Lady Macbeth manipulates him and guilt trips him by saying that he made a promise and that he should not break it, even though he never made a promise to kill Duncan.

*** Macbeth’s response to her about what a man may dare is frequently quoted. What is his meaning?
**** Its meaning is that by hiding that they are the ones who killed Duncan by framing the services and crying and acting sad to the public, they are the ones being fake and are hiding their false and negative hearts, again contributing to the theme of the tragedy.

*** What is the point of Lady Macbeth’s baby imagery? Note the times images of babies and mothers are presented in this play.
**** The point is that she is manipulating Macbeth into killing Duncan by saying that she would do anything for him, including killing a baby for his good, which is obviously very crazy and highly frowned upon.

*** What exposition does Shakespeare give the audience in this scene?
**** Shakespeare creates irony between Macbeth and Lady Macbeth through the contrast of their opinions, as well as indirectly mentions the manipulation of those who love you for their own good. Shows a negative power of love that many do not typically consider.
* Act 2
** Scene 1:
*** What is significant about the weather? (Discuss symbolism)
**** The thing that is significant about the weather is that the moon is down, symbolizing how night is upon us and therefore evil is upon the castle. We associate light with good items and dark with evil

*** What do you suppose is keeping Banquo from sleeping?
**** I suppose that the prophecy, witches, and worrying about macbeth is presenting Banquo from sleeping

*** What is significant about Macbeth’s saying, “I think not of them,” after Banquo had admitted to dreaming about the Weird Sisters?
**** Macbeth is lying to his best friend because he does not want Banquo to be suspicious of his plan to murder the king. Anything that he would say about them would make him a suspect in Banquo’s eyes.

*** What does Macbeth mean when he says to Banquo, “If you shall cleave to my consent, when ’tis, / It shall make honour for you”?
**** Macbeth means that if Banquo supports him if he realizes that Macbeth killed Duncan than it will come to his benefit. He will gain something for keeping quiet.

*** What is significant about Banquo’s reply?
**** It is significant in Banquo’s reply that he says “So I loose none”, which is when he is indirectly questioning if Macbeth is going to do something he shouldnt. It also says that Banquo’s allegiance is to Duncan, so he would kill Macbeth if it came to it.

*** In his soliloquy after Banquo leaves, what does Macbeth tell the audience (readers) he sees? What could account for this apparition?
**** Macbeth tells the audience that he sees the dagger that was used to kill duncan. His guilt could account for this apparition as he is worried and doesnt think that it is a great idea.

*** Why does Shakespeare have Macbeth hallucinate?
**** Shakespeare has Macbeth hallucinate to show how his mind is going crazy and messing with him as he contemplates killing the king, who he is loyal to.

** Scene 2:
*** Compare Macbeth’s and Lady Macbeth’s reactions immediately after the crime.
**** Macbeth is thinking that this is terrible news and is acting shocked. Lady Macbeth also acts shocked by being way more loud and fake about it by fainting or pretending to.

*** Why does Lady Macbeth not commit the murder when she is in the room?
**** She does not commit the murder because Duncan reminded her of her father. Otherwise she says that she had done it.

*** Macbeth, apparently troubled by the murder he has just committed, tells Lady Macbeth what he saw and heard. She tells him, “These deeds must not be thought of this way.” Why?
**** She wants him to forget what happened and just move on thinking that its fine. She wants Macbeth to forget about the guilt and to not think of it as a sin.

*** Macbeth’s response is frequently quoted. What is the sense of this response?
**** The sense of his response is that the deed is going to drive him crazy because he cannot live with the guilt and the constant thought of someone accusing him of the murder.

*** How does Lady Macbeth get Duncan’s blood on her hands?
**** Lady Macbeth gets Duncan’s blood on her hands by using the dagger that was used to kill Duncan.

*** What does Macbeth’s refusal to return to Duncan’s chamber echo?
**** It echos that Macbeth is too light hearted and manipulated into committing such a task. He regrets his decision deeply and wishes to reverse it

** Scene 3:
*** The Porter’s scene, or the “knocking at the gate,” is a much debated scene by scholars, but many agree it is the typical comic relief scene seen in Shakespeare’s plays. What do you suppose the dramatic purpose of a comic relief scene is? Why is the Porter’s soliloquy in prose rather than poetry? What lines contain the bawdy humor so often found in these scenes?
**** The dramatic purpose of a comic relief scene is to juxtapose it with the scene of a tragedy/murder. This is to lighten the mood of the audience after a murder has been committed. The porter’s soliloquy is in prose because it is supposed to show how he is from a lower class and is not as elegant as the rest. Lines 29-37 when he is responding to Macduff and talking about what alcohol causes one to do.
*** How is the theme idea of “a crime against nature” reinforced in this scene?
**** The theme is reinforced through the comparison of Duncan to a church and the devil was the one who killed Duncan. The devil in this case is Macbeth, and this theme is represented by Macduffs explanation of the deed to the others, as he questions why someone would commit such a terrible crime.
*** What does Shakespeare accomplish with Macduff’s allusion to “a new Gorgon”?
**** Shakespeare causes the effect of an inside job/crime in his allusion. He is saying that someone did not protect the castle as a gorgon is a mythical creature that is supposed to turn evil into stone, creating the effect in the audience of contrast in that Macbeth committed the crime even though he was supposed to be defending the king.
*** How does Macbeth react to the discovery of Duncan’s body?
**** Macbeth reacts to the discovery of Duncan’s body by stating that he would have rather died than see the sight of his dead king, and the audience realizes how he is being truthful and how guilt has overwhelmed him.
*** How does Lady Macbeth react?
**** Lady Macbeth reacts by asking for help as she faints to the ground. She might also be drawing the suspicion off of Macbeth by causing a distraction, but that is rather unlikely as she likely does not have his back. People think that she is too soft and would never think of committing such an evil crime.
*** Who is the one who points out the inappropriateness of Lady Macbeth’s initial response?
**** Macduff, as Lady Macbeth acts annoyed by the bell but Macduff knows the crime that has commited. Macduff states that she is too fragile of a woman and would faint if she heard what had happened in the night.
*** What is the predominant image in this scene, and what effect does it create?
**** The predominant image is a facade in that Lady Macbeth and Macbeth are both acting fake. This creates the effect of something unusual happening here, which is later expanded in scene 4 by the old man and ross.
*** What double meaning might Shakespeare have intended for Macbeth’s line, “He does: he did appoint so,” in response to Lennox’s asking, “Goes the King hence today?”
**** Shakespeare intended that Duncan intended to leave today but Macbeth knows that he won't because he killed him in his sleep.

** Scene 4:
*** What is the purpose of this scene?
**** The purpose of this scene is to show how unusual and weird the crime was. The two are trying to figure out who committed it, but they don't understand the motives behind the servants doing so. This is possibly hinting at Duncan's two sons receiving the blame because they are the ones who are fleeing and leaving the country. We know that this is because they think that they are going to be killed next.

*** What additional natural, or “unnatural,” events further the “crime against nature” theme?
**** The events that further the crime against nature theme are that because the two believe the servants had no motive to do it, and that the two sons are leaving the country but they think it is not because they bribed anyone, then the most likely person who would have commited the crime would be Macbeth, but he is said to be loyal to the King and such an honorable person, and it would not be right if he killed the person he cared about.

* Act 3
** Scene 1:
*** In his soliloquy, what suspicion and hope does Banquo reveal?
**** Banquo reveals that he is suspicious of Macbeths treason and murder of king Duncan. He hopes that Macbeth did not take the witches prophecy into his own hands and that his friend is still good.

*** Macbeth seems to be very interested in Banquo’s travel plans. Why do you suppose he is so interested?
**** Macbeth is very interested in Banquo’s travel plans because he wants to know where he is and at what time inorder for the two murders to murder him. It would be wise to do it away from Macbeth's location so that he is not a suspect.

*** The speech beginning “To be thus is nothing...” is another one often quoted. What is the meaning of that sentence?
**** The meaning of that sentence is that to be King is nothing, but to be safely king is remarkable. This is because as a King, you almost always have a target on your back as someone wants to kill you.

*** What is there in Banquo’s character that makes Macbeth uneasy?
**** Macbeth is uneasy because he fears how Banquo is the good as he is honest and loyal, and fears that he will avenge the king and betray his friend.

*** What is there in the situation with Banquo that particularly upsets Macbeth?
**** Macbeth is upset that Banquo’s sons will be the air to the throne because he is a fruitless crown, meaning he has no offspring and therefore the royal crown will not be in his blood. Banquo’s sons basically benefit from no troubles at all.

*** What does Shakespeare offer in Macbeth’s conversation with the murderers?
**** Shakespeare on the surface offers that Macbeth would do it himself if he was not king, but he is really stating that Macbeth will not have the ability to kill his best friend himself because there is still some good in him.

*** How does Macbeth convince the murderers to kill Banquo and Fleance?
**** Macbeth manipulates the murders into thinking that Banquo is their enemy and has betrayed them. He makes them think that nothing should stop them from killing Banquo, which is why they are willing to kill Fleance.

*** What does Macbeth tell them to do?
**** Macbeth tells them to kill Banquo and Fleance tonight before supper while he is off and away riding his horse. He tells them to make sure the deed is done and to end it here once and for all.

** Scene 2:
*** What is the meaning of Lady Macbeth’s opening speech in this scene?
**** Lady Macbeth's opening speech reveals how she is scared and worries that things will not turn out well. It shows that she might of just been going along with her husband and that she might truly be regretting the murder they commited. However, when she talks to Macbeth, she is back to her crazy relentless personality.

*** In this scene, what is Macbeth’s state of mind?
**** Macbeth’s state of mind is paranoia and is scared for his life. He wishes he was dead and that because of the betrayal of those close to him he is going to hell so becoming more evil is not as much of an issue anymore. He thinks that he must betray Banquo even though Banquo never said that he would harm Macbeth.

*** How does Macbeth show that his resolve and ambition have become stronger?
**** Macbeth shows that his resolve and ambition have become stronger when Shakespeare hints that he has been possessed by evil through his rhymes similar to the witches. He also states that Lady Macbeth doesnt need to know about the murder and that she will be happy and proud, when in reality Lady Macbeth isnt worried about Banquo and would oppose his plan.

*** What is significant about Macbeth’s instructions to Lady Macbeth about how to treat Banquo at the state dinner that night?
**** Macbeth's instructions to Lady Macbeth are to be fake and phony and act normal like nothing happened. Macbeth is continuing the theme of the fair is foul, and foul is fair. The importance of this is that Macbeth has become how Lady Macbeth was acting when planning Duncan’s murder, revealing that he has become more evil and has poorer inentions than before killing Duncan.

** Scene 3:
*** What happens at the ambush?
**** The three murders kill Banquo but Fleance escapes. They decide not to chase after him as they only thought Banquo was their real enemy, and go to tell Macbeth of the news.

*** Given the previous scene in which Banquo’s death is planned, and the next scene in which the audience could learn with Macbeth that Fleance has escaped, why would Shakespeare choose to dramatize this seemingly insignificant event?
**** Shakespeare chooses to dramatize this event because he is foreshadowing how Fleance will have revenge on him, whether it is mentally or physically. Macbeth will always be mentally haunted in that he will be paranoid that Fleance will come back to kill him.

** Scene 4:
*** One characteristic of Shakespeare’s style is his play on words. How is this demonstrated in Macbeth’s response to the murderer’s saying it’s Banquo’s blood on his face?
**** The normal saying is that there is blood on your hands, meaning that the person has murdered someone and the guilt surrounds them. Macbeth’s response further entails that it is better that Banquo died than if he was alive, further proving Macbeth's paranoia and fear of other’s revenge.

*** What wordplay is there in the murderer's reply that Banquo is “safe” now?
**** Banquo is safe in that he is 100% dead and in heaven, aka “safe” in that he can not be harmed in the future. The play on words is that Macbeth is the one who is safe because he no longer has to worry about Banquo avenging King Duncan.

*** The dagger Macbeth saw in Act II, scene i was a hallucination. Banquo’s ghost in this scene is not. How do we know?
**** We know this is not a hallucination because Macbeth refuses to sit in the seat of Banquo’s ghost and talks to the Ghost as if it is a person. Macbeth also asks who pulled this prank on him to the others, trying to play it off, but still refuses to sit.

*** What does Lady Macbeth say to Macbeth?
**** Lady Macbeth says that he is not Manly enough and strong enough and that he is acting like a weak woman, actually like a womens grandmother. She insults him for how he is acting and says that he is shameful.

*** What is the significance of the conversation Macbeth and Lady Macbeth have immediately after the guests leave?
**** The significance is that they can not tell what is good and what is evil anymore and think that they are trapped in an endless cycle of violence. “It will have blood, blood will have blood”. Both kind of act humanly in that they are both good and evil, as in one can be all of one thing, but humanity as a whole is a mixture of both.

*** For what reason does Macbeth mention Macduff’s name?
**** Macbeth mentions Macduff’s name because he is suspicious that he did not show up. He is starting to think that Macduff knows what's going on and is plotting revenge against Macbeth, which we later find out that he is.

*** What does Macbeth say he will do next?
**** Macbeth says that he will go visit the witches and hear out their prophecy. He also states that he is selfish in that he only cares now about what happens to himself and does not care about the people of scotland

*** What is Macbeth’s frame of mind?
**** Macbeth’s frame of mind is that there is more coming. More blood that will be on their hands and things that will go poorly. He has a strong feeling people are plotting against him and coming for him, and therefore has a strong paranoia about Banquo and Duncan’s sons.

** Scene 5:
*** Who is Hecate, and why is she angry?
**** Hecate is the god of witches. She is angry because the three witches went behind her back without her knowledge and cursed macbeth. She realizes she must fix the problem they created herself.

*** What is her plan for Macbeth?
**** Hecate plans to convince Macbeth that he will never die and make him so confident that it will lead to his downfall. Will tell him through the three sisters not to fear death and that he has safely secured the throne.

** Scene 6:
*** How can we interpret Lennox’s speech?
**** We can interpret Lennox’s speech as one with safely guarded words. Lennox is worried that the lord he is talking to might snitch or be a spy for Macbeth, so he chooses his words with care.

*** What further exposition does Shakespeare offer through the Lord?
**** The lord reveals that Macduff is requesting the help of England to remove Macbeth from the throne, and aligns himself with Macduff and not Macbeth. Shakespeare allows us to consider that because Banquo’s sons will take the throne, Duncan’s two sons will die in battle trying to avenge their father but Fleance will succeed and take the throne with the blood of Macbeth on his hands.

* Act 4
** Scene 1:
