#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:0 h:2 toc:1
# num:0 = dont number any, h:2 = headings to level 2, toc:1 = only put a table of contents to level 1
#+TITLE:     Physics All Subjects notes
#+AUTHOR:    Alex Burns
# EXPORT = C-c C-e h h

# https://github.com/fniessen/refcard-org-mode
# https://orgmode.org/worg/org-symbols.html
# /Emphasize/ (italics), *strongly* (bold), and */very strongly/* (bold italics).
# num:1 = numbering up to level 1 heading; num:nil = numbering for all headings

* Kinematics
** Equations
 $x=\frac12at^2$ \\
 $a=v/t$ \\
 $V^2=v^2+2ax$ \\
 $V=d/t$ \\
 $\Delta d=\frac12(v_f+v_i) \Delta t$ \\
** Graphs
** Practice Problems
- How do we calculate speed? Or velocity?
- What do distance versus time graphs show? What do the different slopes mean?
- What is acceleration?
- When do you use d=st to solve for distance, and when do you have to use x=1/2at2?
- When do you use s=d/t to solve for speed, and when do you have to use v=at?
- If we have a curved line when we graph data (like on a distance vs time graph when an object is accelerating), what are the three different ways we can determine speed at a certain point?
- How can we use the idea of freefall (g=-10m/s2) to solve problems for falling objects?
- How can we determine the distance a projectile travels if we know the initial conditions of the object?
- What do we know about the horizontal and vertical components of a projectile as it travels?

* Forces
** Big Ideas
- A force is a psuh or a pull on an object
- Adding up all of the forces on an object will give you the total (*NET*) force on the object
- If there is a net force acting on an object, the object will accelerate; if there is no net force the object will maintain a constant (and possibly zero) velocity
- We can think of forces acting on individual objects or an entire "system" of objects. In either case, Newton's 2nd Law: F=ma, still applies
- Linking forces to other physics topics:
  - Kinematics: Forces cause accelerations or changes in velocity
  - Momentum: Forces cause changes in momentum (impulses)
  -  Energy: Forces act on objects to change the kinetic energy through doing work on such objects
  - Oscillations: Forces can oppose motion. When this happens an object will oscillate around a fixed point
  - Rotation: Forces causing rotations act at a distance "r" from the point of rotation and are called "torques"
** What do I really need to remember for the test?
- You should be able to correctly identify which forces are acting on an object (or a system) at any moment. Remeber, the forces include: gravity, friction, normal, tension, and applied. Generally, air resistance is negligible
- Make sure you can correctly draw a force diagram. Your force vectors should be drawn neatly and to scale, starting on the object and poitning outward
- Take a moment to think about which force is larger for a problem without applying any math. Many times students will assume certain relationships that are common, but not always true.  For instance, the normal is often, but not always, equal to gravity.  For a block hangin by a string, tension may or may not be equal to gravity.  Double check the problem carefully!
- Always start mathematical operations with an equation from the formula sheet.  If you are looking for gravity or friction use Fg=mg and f=μN, respectively.  Solving for centripetal force or the gravitational force between planets, use their respective equations.  If you see a block on a ramp and you say F(II)=mg $\sin(\theta)$ you will lose points as you have not shown where this equation came from and how it is derived.
** Equations
*** General
$F=ma$ \\
$Fg=mg$ \\
*** Elevator
$T-Fg=ma$ \\
*** Ramps
$F_N=mg\cos(\theta)$ \\
$F(II)=mg\sin(\theta)$ \\
$F_f=uN=umg\cos(\theta)$ \\
$tan(\theta)=u$ \\
** Graphs
** Practice Problems
- What are Newton’s three laws?
- If an object has a=0, what else must be true? (There are 4 things)
- What does it mean when forces are balanced? Or equilibrium?
- How does the force applied on object A by object B compare to the one applied by object B on object A? (Which law is that?)
- How does net force relate to acceleration?
- How is normal force determined?
- What are some examples of situations in which the normal force is not equal to an object’s weight?
- When should you consider breaking forces up into component?

* Gravity/Circular Motion
** Equations
$F_G=G(m_1m_2)/r^2$ \\
$F_c=mv^2/r$ \\
$T^2=(4\pi ^2/GM)r^3$ \\
** Graphs
** Practice Problems
- If something is moving in a circle, what must be true about the net force on it? The acceleration?
- What do we call the net force acting on an object travelling in a circle?
- How do we calculate Fc? How does it change if we increase the mass?  The velocity? The radius?
- The Fc is always caused by some force (or sum of forces). For example, for the moon going around the sun, the Fc is caused by gravity. It can be a single force, a component of one force, or the sum of multiple forces. Give an example of each.
- How does the centripetal force change when a roller coaster is at the top of a loop versus at the bottom of a loop?
- What caused the centripetal force on the toy airplane in the lab we did? How did we determine the magnitude (value) of the radius and of the centripetal force?
- How is the force of gravity between two planets affected by their masses? Their distance apart?
- How is the big equation for gravity (Gmm/r2) related to the weight equation (F=mg)?
* Energy
** Equations
$PE=mgh$ \\
$KE=\frac12 mv^2$ \\
$KE(ROT)=\frac12Iw^2$ \\
$U_s=\frac12kx^2$ \\
$W=Fx\cos(\theta)$ \\
** Graphs
** Practice Problems
- What is “work” in a physics context?  How is it related to the outside force?
- When does someone do more work or less?
- How is work related to energy?
- How do you determine gravitational PE?
- How do you determine kinetic energy?
- What does it mean to say that energy is conserved? Or transferred?
- How are KE and PE related? (How is the height an object begins at related to its speed at h=0?)
- What is power and how does it relate to energy?
- How can elastic energy convert into kinetic energy? Or potential?
* Momentum
** Equations
$p=mv$ \\
$\Delta p =m \Delta v$ \\
$\Delta p = F \Delta t$ \\
$m_1v_1+m_2v_2=m_1v_1^\prime + m_2v_2^\prime$ \\
$\frac12 m_1v_1^2+\frac12m_2v_2^2 = \frac12 m_1v_1^2 + m_2v_2^2$ \\
** Graphs
** Practice Problems
- How do you determine momentum?
- What does it mean to say that momentum is conserved?
- What is the difference between elastic and inelastic collisions?
- What is true about the forces on the two objects that are colliding (regardless of mass!)?
- What is Impulse?
- How is impulse related to the outside force?
* Oscillations & Waves
** Equations
$T=2\pi\sqrt{L/g}$ \\
$T=2\pi\sqrt{m/k}$ \\
$T=1/f$ \\
** Graphs
** Practice Problems
- What is an oscillation?  What are some common examples of oscillations?
- What factors determine the time it takes for things to oscillate (springs and pendulums)
- What is a wave?  What are some examples of waves?  How are waves organized?
- Compare and contrast different types of waves.
- How are the various wave characteristics related?  (ie… period, frequency, wavelength, and wave speed)
- What are some characteristics of sound waves and light waves?
- How are open-ended tubes similar and different from closed-ended tubes?
- How does your eye perceive color?
- How do colors mix with light as compared to pigments?
* Rotation
** Equations
*** Torque
$\tau=Fr\sin(\theta)$ \\
$\tau=I\alpha$ \\
$I=kmR^2$ \\
*** Connecting
$x=R\theta$ \\
$v=R\omega$ \\
$a=R\alpha$ \\
*** General
$\theta = \frac12 \alpha t^2$ \\
$\omega_f^2=\omega^2 + 2\alpha \theta$ \\
$\alpha = \omega / t$ \\
$\omega = \theta /t$ \\
** Graphs
** Practice Problems
- How are the rotational motion terms defined?  What is a radian?  How do we measure rotational motion quantities?
- What is torque in all of its complexity?
- What is the center of mass of an object?  How can multiple objects have a center of mass? How can you find the center of mass?
- Why do things balance?  How is balancing related to torque?
- How does net torque relate to net force?
- How does the torque on an object relate to the rotational acceleration of an object?
- How does a pulley work when we include the rotation/torque on the pulley?
- Why does a ball roll down a hill and a box does not?
- How does the shape of a round object affect its ability to roll down a hill?  Which shape is the best for rolling down a hill in terms of speed?
