#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:0 h:2 toc:1
# num:0 = dont number any, h:2 = headings to level 2, toc:1 = only put a table of contents to level 1
#+TITLE:     Physics All Subjects notes
#+AUTHOR:    Alex Burns
# EXPORT = C-c C-e h h

# https://github.com/fniessen/refcard-org-mode
# https://orgmode.org/worg/org-symbols.html
# /Emphasize/ (italics), *strongly* (bold), and */very strongly/* (bold italics).
# num:1 = numbering up to level 1 heading; num:nil = numbering for all headings

* Kinematics
** Equations
 $x=\frac12at^2$ \\
 $a=v/t$ \\
 $V^2=v^2+2ax$ \\
 $V=d/t$ \\
 $\Delta d=\frac12(v_f+v_i) * \Delta t$ \\
** Graphs
** Practice Problems
* Forces
** Big Ideas
- A force is a psuh or a pull on an object
- Adding up all of the forces on an object will give you the total (*NET*) force on the object
- If there is a net force acting on an object, the object will accelerate; if there is no net force the object will maintain a constant (and possibly zero) velocity
- We can think of forces acting on individual objects or an entire "system" of objects. In either case, Newton's 2nd Law: F=ma, still applies
- Linking forces to other physics topics:
**** Kinematics: Forces cause accelerations or changes in velocity
**** Momentum: Forces cause changes in momentum (impulses)
**** Energy: Forces act on objects to change the kinetic energy through doing work on such objects
**** Oscillations: Forces can oppose motion. When this happens an object will oscillate around a fixed point
**** Rotation: Forces causing rotations act at a distance "r" from the point of rotation and are called "torques"
** What do I really need to remember for the test?
- You should be able to correctly identify which forces are acting on an object (or a system) at any moment. Remeber, the forces include: gravity, friction, normal, tension, and applied. Generally, air resistance is negligible
- Make sure you can correctly draw a force diagram. Your force vectors should be drawn neatly and to scale, starting on the object and poitning outward
- Take a moment to think about which force is larger for a problem without applying any math. Many times students will assume certain relationships that are common, but not always true.  For instance, the normal is often, but not always, equal to gravity.  For a block hangin by a string, tension may or may not be equal to gravity.  Double check the problem carefully!
- Always start mathematical operations with an equation from the formula sheet.  If you are looking for gravity or friction use Fg=mg and f=μN, respectively.  Solving for centripetal force or the gravitational force between planets, use their respective equations.  If you see a block on a ramp and you say F(II)=mg $\sin(\theta)$ you will lose points as you have not shown where this equation came from and how it is derived.
** Equations
*** General
$F=ma$ \\
$Fg=mg$ \\
*** Elevator
$T-Fg=ma$ \\
*** Ramps
$F_N=mg\cos(\theta)$ \\
$F(||)=mg\sin(\theta)$ \\
$F_f=uN=umg\cos(\theta)$ \\
$tan(\theta)=u$ \\
** Graphs
** Practice Problems
* Gravity/Circular Motion
** Equations
$F_G=G(m_1m_2)/r^2$ \\
$F_c=mv^2/r$ \\
** Graphs
** Practice Problems
* Energy
** Equations
$PE=mgh$ \\
$KE=\frac12 mv^2$ \\
$KE(ROT)=\frac12Iw^2$ \\
$U_s=\frac12kx^2$ \\
$W=Fx\cos(\theta)$ \\
** Graphs
** Practice Problems
* Momentum
** Equations
$p=mv$ \\
$\Delta p =m \Delta v$ \\
$\Delta p = F \Delta t$ \\
$m_1v_1+m_2v_2=m_1v_1^\prime + m_2v_2^\prime$ \\
$\frac12 m_1v_1^2+\frac12m_2v_2^2 = \frac12 m_1v_1^2 + m_2v_2^2$ \\
* Oscillations
** Equations
$T=2\pi\sqrt{L/g}$ \\
$T=2\pi\sqrt{m/k}$ \\
$T=1/f$ \\
** Graphs
** Practice Problems
* Rotation
** Equations
*** Torque
$\tau=Fr\sin(\theta)$ \\
$\tau=I\alpha$ \\
$I=kmR^2$ \\
*** Connecting
$x=R\theta$ \\
$v=R\omega$ \\
$a=R\alpha$ \\
*** General
$\theta = \frac12 \alpha t^2$ \\
$\omega_f^2=\omega^2 + 2\alpha \theta$ \\
$\alpha = \omega / t$ \\
$\omega = \theta /t$ \\
