#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:0 h:2 toc:2
# num:0 = dont number any, h:2 = headings to level 2, toc:1 = only put a table of contents to level 1
#+TITLE:     Vocabulary
#+AUTHOR:    Alex Burns
# EXPORT = C-c C-e h h

# https://github.com/fniessen/refcard-org-mode
# /Emphasize/ (italics), *strongly* (bold), and */very strongly/* (bold italics), \\ = return

* Chapter 1:
** Section 1:
*** Individuals: the objects described by a set of data. Individuals may be people, animals, or things
*** Variable: any characteristic of an individual. A variable can take different values for individuals
*** Categorical variable: places an individual into one of several groups or categories
*** Quantitative variable: takes numerical values for which it makes sense to find an average
*** Distribution: The pattern of variation of a variable. Tells us what values the variable takes and how often it takes these values
*** Inference: Drawing conclusions from the data at hand
*** Pie Chart: Shows the distribution of a categorical variable as a “pie” whose slices are sized by the counts or percents for the categories
*** Bar Graphs: Represent each category as a bar. The height of the bar shows the category counts or percents. Are easier to make and easier to read
*** Segmented Bar Graph: A bar graph where each category of a larger group (male or female for example) is stacked vertically. Able to easily compare the two groups
*** Marginal Distributions: Appear at the right and bottom margins of the two-way table. The subtotal out of the total. Tells us nothing about the relationship between two categorial variables
*** Conditional Distribution: Describes the values of that variable among individuals who have a specific value of another variable
*** Association: If knowing the value of one variable helps predict the value of another
*** Two-Way Table: Organizes data about two categorical variables measured for the same set of individuals. Summarizes large amounts of information by grouping outcomes into categories
*** Frequency Table: Shows the count of various outcomes in a sample
*** Relative Frequency Table: Represents the counts of various outcomes in a sample as percentages. Needs to show the fraction, ex 1/2, then the percent, ex 50%
*** Round-off Error: The error between an approximate and the exact mathematical result. Common with percents as they are rounded

** Section 2:
*** Dotplot: One of the simplest to construct. Each data value is a dot above its location on a number line
*** Outlier: An individual value that falls outside the overall pattern
*** Mode: The most common value, data point with the highest frequency
*** Symmetric: If the right and left sides of the graph are approximately mirrored images of each other
*** Skewness: Skewed to the right (positive skew) = all values on left side, low amount on right side. Downwards staircase. Skewed left = all values on right side/staircase
*** Unimodal: Having only one peak
*** Bimodal: Having two clear peaks
*** Multimodal: Having three or more peaks
*** Stemplot: A graphical display for fairly small data sets. Give us a quick picture of the shape of distribution while including the actual numerical values
*** Back to Back StemPlot: Two stem plots are put back to back with the common stem in the middle. The leaves are ordered outwards from the common stem
*** Histogram: Groups nearby values together for quantitive variables. It is an approximate representation of the data
*** Class: A grouping of values typically for a histogram
*** Range: The difference between the greatest and lowest value
*** Median: The middle value. The center value in a set of data
*** Mean: The average of data, add up the values then divide by total number

** Section 3:
*** Mean: the most common measure of center which is the ordinary arthmetic average. X bar, x^_, or mew, u. The mean is sensitive to the influence of extreme observations so several far away outliers would cause the mean to be a worse measure of center. A mean is not a resistant measure of center
*** Median: the midpoint of a distribution. The number such that half of the oversvations are bigger and half are smaller. A median is a resistant measure of center
*** Range/Variance: The difference between the maximum and minimum values of a data set
* Chapter 2:
** Section 1:
*** Percentile: the pth percentile of a distribution is the value with p percent of the observations less than it
*** Cumlative Relative Frequency Graph: Plot a point corresponding to the cumulative relative frequency in each class at the smallest value of the next class
*** Z-Score (Standarized Score): tell us how many standard deviations from the mean an observation falls, and in what direction
*** Transforming data: Converting the original observation from the original units of measurement to a standardized scale
