#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:0 h:2 toc:2
# num:0 = dont number any, h:2 = headings to level 2, toc:1 = only put a table of contents to level 1
#+TITLE:     Vocabulary
#+AUTHOR:    Alex Burns
# EXPORT = C-c C-e h h

# https://github.com/fniessen/refcard-org-mode
# /Emphasize/ (italics), *strongly* (bold), and */very strongly/* (bold italics), \\ = return

* Chapter 1:
** Section 1:
*** Individuals: the objects described by a set of data. Individuals may be people, animals, or things
*** Variable: any characteristic of an individual. A variable can take different values for individuals
*** Categorical variable: places an individual into one of several groups or categories
*** Quantitative variable: takes numerical values for which it makes sense to find an average
*** Distribution: The pattern of variation of a variable. Tells us what values the variable takes and how often it takes these values
*** Inference: Drawing conclusions from the data at hand
*** Pie Chart: Shows the distribution of a categorical variable as a “pie” whose slices are sized by the counts or percents for the categories
*** Bar Graphs: Represent each category as a bar. The height of the barshows the category counts or percents. Are easier to make and easier to read
*** Marginal Distributions: Appear at the right and bottom margins of the two-way table. The subtotal out of the total
